### ISSUE TITLE
& in examples not escaped in HTML

### ISSUE THREAD

**Issue by CyberShadow** [rejectedsoftware/ddox#105]
http://dlang.org/library/core/exception/object.factory.html

Note the line: 
```
    assert(c !is null && c.x == 10);
```

It appears that way in the HTML source, i.e. the `&` characters are not escaped.

I'm guessing this is a bug, but it might also be that DDox is taking advantage of HTML5's lenient validation of unescaped entities, which make that line "valid" HTML5. If it's the latter case, could this be disabled for dlang.org, as it's making it difficult to validate the produced HTML?

**Comment by CyberShadow** [comment]
Thanks

**Comment by s-ludwig** [comment]
BTW, it was actually a bug, escaping was only done for backtick-code.

**Comment by CyberShadow** [comment]
How can I try this fix? Can I put the commit hash in dub.json OSLT?

**Comment by s-ludwig** [comment]
Commit hashes don't work yet, but you can use `"~master"`, preferably in dub.selections.json, but dub.json will work, too. I'll create a new version tag tomorrow if nothing else comes up.
