### ISSUE TITLE
Object.factory and others in unrelated modules' documentation

### ISSUE THREAD

**Issue by CyberShadow** [rejectedsoftware/ddox#106]
http://dlang.org/library/core/exception/object.factory.html
http://dlang.org/library/core/sync/barrier/object.factory.html
http://dlang.org/library/core/sync/condition/object.factory.html
http://dlang.org/library/core/sync/exception/object.factory.html
http://dlang.org/library/core/sync/mutex/object.factory.html
http://dlang.org/library/core/sync/rwmutex/object.factory.html
http://dlang.org/library/core/sync/semaphore/object.factory.html
http://dlang.org/library/core/thread/object.factory.html
http://dlang.org/library/core/time/object.factory.html
http://dlang.org/library/object/object.factory.html <- the correct one
http://dlang.org/library/std/base64/object.factory.html
http://dlang.org/library/std/concurrency/object.factory.html
http://dlang.org/library/std/container/rbtree/object.factory.html
http://dlang.org/library/std/conv/object.factory.html
http://dlang.org/library/std/csv/object.factory.html
http://dlang.org/library/std/datetime/object.factory.html
http://dlang.org/library/std/digest/digest/object.factory.html
http://dlang.org/library/std/encoding/object.factory.html
http://dlang.org/library/std/exception/object.factory.html
http://dlang.org/library/std/file/object.factory.html
http://dlang.org/library/std/getopt/object.factory.html
http://dlang.org/library/std/json/object.factory.html
http://dlang.org/library/std/mmfile/object.factory.html
http://dlang.org/library/std/net/curl/object.factory.html
http://dlang.org/library/std/numeric/object.factory.html
http://dlang.org/library/std/outbuffer/object.factory.html
http://dlang.org/library/std/parallelism/object.factory.html
http://dlang.org/library/std/process/object.factory.html
http://dlang.org/library/std/range/interfaces/object.factory.html
http://dlang.org/library/std/socket/object.factory.html
http://dlang.org/library/std/stdio/object.factory.html
http://dlang.org/library/std/string/object.factory.html
http://dlang.org/library/std/typecons/object.factory.html
http://dlang.org/library/std/uri/object.factory.html
http://dlang.org/library/std/utf/object.factory.html
http://dlang.org/library/std/uuid/object.factory.html
http://dlang.org/library/std/variant/object.factory.html
http://dlang.org/library/std/xml/object.factory.html
http://dlang.org/library/std/zip/object.factory.html
http://dlang.org/library/std/zlib/object.factory.html

**Comment by s-ludwig** [comment]
Fixed by 0906343a555b36749cd4b48c2dcdbd61d3e22ba4 (same cause as #120).
