### ISSUE TITLE
Cross-linking to package.d modules

### ISSUE THREAD

**Issue by JakobOvrum** [rejectedsoftware/ddox#110]
Original title: Module references at the end of a punctuated sentence should be detected
---

e.g.
```
See std.algorithm.
```
Should make `std.algorithm` a link to that module.

**Comment by s-ludwig** [comment]
I've tested the following:
```
///
module test;

/** This is referencing bar.

	This is not referencing bar.bar or anything else.

	Finally another bar reference to bar.
*/
void foo()
{

}

///
void bar()
{

}
```
All three `bar` references have been correctly detected. I think the issue here was just that `std.algorithm` in particular gets detected as a package rather than a module. I'll have a look at that.

**Comment by JakobOvrum** [comment]
Great, thanks!
