### ISSUE TITLE
Function with auto return type parsed as {null}

### ISSUE THREAD

**Issue by ZombineDev** [rejectedsoftware/ddox#111]
I have something close this
```D
struct MyRange(T)
{
    auto front() const
    {
        //...
    }
}
```
Which produces the following:

```JSON
{
	"file": "[...]",
	"name": "[...]",
	"members": [
		{
			"members": [
				{
					"name": "MyRange",
					"line": 245,
					"members": [
						{
							"endchar": 4,
							"name": "front",
							"line": 265,
							"comment": "[...]",
							"type": "const ()",
							"endline": 275,
							"char": 9,
							"kind": "function",
							"storageClass": [
								"auto"
							]
						}
					],
					"char": 1,
					"kind": "struct"
				}
			],
			"name": "MyRange",
			"line": 245,
			"comment": "...",
			"parameters": [
				{
					"name": "T",
					"kind": "type"
				}
			],
			"char": 1,
			"kind": "template"
		}
	],
	"comment": "[...]",
	"kind": "module"
}
```
The important parts being `"type": "const ()"` and `"storageClass": [  "auto" ]`.

While the documentation is parsed I get the following error:

```
Error parsing type 'const ()': Expected identifier but got )
```
(Probably from [this](https://github.com/rejectedsoftware/ddox/blob/master/source/ddox/parsers/jsonparser.d#L373) and [this](https://github.com/rejectedsoftware/ddox/blob/master/source/ddox/parsers/jsonparser.d#L503) lines.)

And in the HTML output per function I get:
```
{null} front();
```
Probably DMD should output `"type": "const void()"`, but still I would expect functions with auto return type to be common enough to be handled properly in DDOX.

**Comment by s-ludwig** [comment]
Same as #94. Looks like DMD is missing the "deco" field that it should output in addition to the human readable "type" field.
