### ISSUE TITLE
(Semi-)invisible examples with default formatting

### ISSUE THREAD

**Issue by John-Colvin** [rejectedsoftware/ddox#113]
E.g. https://github.com/DlangScience/scid/blob/master/source/scid/core/testing.d#L13 becomes https://dlangscience.github.io/scid/api/scid/core/testing/isAccurate.html

In the code in the ddoc comment, operators are in a very light grey and the rest is white.

**Comment by s-ludwig** [comment]
Which version did you test with? There was a related fix in d225c6ef that went into v0.11.1 (2015/10/15). I've tested with master and got a black background for the code block.

**Comment by s-ludwig** [comment]
Confirmed working on master.
