### ISSUE TITLE
macros from parent scopes are not known in child scopes

### ISSUE THREAD

**Issue by aG0aep6G** [rejectedsoftware/ddox#116]
With dmd, macro definitions from parent scopes are available in child scopes. ddox doesn't do this.

Example:

```d
/**
Macros:
MODULE_MACRO=module macro
*/
module test4;

/// $(MODULE_MACRO)
void f() {}

/**
Macros:
STRUCT_MACRO=struct macro
*/
struct S
{
    /// $(MODULE_MACRO) $(STRUCT_MACRO)
    void g() {}
}
```

dmd's output is "module macro" for `f`, and "module macro struct macro" for `S.g`. ddox's doesn't generate any documentation.

The Ddoc spec doesn't seem to spell this out, but it has an example implying that macro definitions should be available in sub-scopes (first example under the "Macros" heading on <http://dlang.org/spec/ddoc.html>):

```d
/**
Macros:
 PARAM = <u>$1</u>
 MATH_DOCS = <a href="https://dlang.org/phobos/std_math.html">Math Docs</a>
*/
module math;

/**
 * This function returns the sum of $(PARAM a) and $(PARAM b).
 * See also the $(MATH_DOCS).
 */
int sum(int a, int b) { return a + b; }
```

**Comment by quickfur** [comment]
Related: https://issues.dlang.org/show_bug.cgi?id=15673
