### ISSUE TITLE
ddox duplicates declarations

### ISSUE THREAD

**Issue by g4z3r** [rejectedsoftware/ddox#120]
Situation:
```
module mod;

class Base {
   int field;
}

class A : Base {
}
```
In this case ddox duplicates `field` declaration on `Base.field` page as many times as the module has `Base` subclasses. [Look](http://cs621524.vk.me/v621524987/b797/xiv8d9V4SAA.jpg)

**Comment by s-ludwig** [comment]
I've seen this happen, but for some reason it's not reproducible for me now. If it still happens for DDOX master, can you post the compiler version and/or the json file that was generated? Maybe it already happens in an earlier stage.

**Comment by g4z3r** [comment]
Bug is still present. Done simply with `dub build -b ddox`, ddox version is 0.15.0 (master), dmd version is 2.071.0-0.
docs.json:
```
[
	{
		"file": "source/app.d",
		"name": "mod",
		"members": [
			{
				"name": "Base",
				"line": 3,
				"members": [
					{
						"offset": 16,
						"name": "field",
						"line": 4,
						"deco": "i",
						"char": 6,
						"kind": "variable"
					}
				],
				"char": 1,
				"kind": "class"
			},
			{
				"members": [],
				"name": "A",
				"line": 7,
				"base": "mod.Base",
				"char": 1,
				"kind": "class"
			}
		],
		"kind": "module"
	}
]
```

**Comment by s-ludwig** [comment]
OK, it just happened for "generate-html" and I used to test with "serve-html". Fixed now.
