### ISSUE TITLE
Methods are duplicated when generating docs on Windows

### ISSUE THREAD

**Issue by MyLittleRobo** [rejectedsoftware/ddox#123]
[Example from online dlangui docs](http://buggins.github.io/dlangui/ddox/dlangui/widgets/widget/Widget.checkChange.html)

Seems like it generates duplicates if method is (re-)implemented in derived class.

I don't face this issue on Linux.

**Comment by s-ludwig** [comment]
Which version was used to generate those docs? Supposedly this issue has been fixed recently: #120

**Comment by MyLittleRobo** [comment]
You are right. I upgraded ddox and issue gone.
