### ISSUE TITLE
Macro argument order evaluation issue

### ISSUE THREAD

**Issue by s-ludwig** [rejectedsoftware/ddox#130]
Originally reported by @andralex:
```
IGNORESECOND = [$1]
DOLLARZERO = dzbegin $0 dzend
TEST = before $(IGNORESECOND $(DOLLARZERO one, two)) after 
```
`$(TEST)` yields `before [dzbegin one, two dzend] after` when evaluated by Ddoc, but `before [dzbegin one] after` when evaluated by DDOX.

**Comment by andralex** [comment]
thx!

**Comment by MartinNowak** [comment]
Should we tag a new point release and update dpl-docs?
