### ISSUE TITLE
Problems with extern (C++)

### ISSUE THREAD

**Issue by jpiles** [rejectedsoftware/ddox#131]
Hi! Apparently `extern (C++)` is not supported by ddox:

```
module test;

extern (C++) public void foo() {}

void main() {
	foo();
}
```

> $ dmd -Xfdocs.json test.d # It compiles properly
> $ ddox generate-html --navigation-type=ModuleTree docs.json docs
> Reading doc file...
> Parsing JSON...
> Parsing docs...
> Error parsing type 'extern (C++) void function()': Enforcement failed
> Expected function type for ''/'extern (C++) void function()', got Primitive extern (C++) void function()
> Finished parsing docs.
> Generating module: test

In this case I get this function signature:

> {null} foo();

If I switch from `extern (C++)` to `extern (C)` everything works as expected, and I get:

> extern(C) void foo();

I have tried with the latest git master version of ddox (commit `cb1968c`).

**Comment by jpiles** [comment]
After a bit of investigation, I guess the problem lies either [here](https://github.com/rejectedsoftware/ddox/blob/cb1968cbe1aa9540130117dd592ff936bdea8b7d/source/ddox/parsers/jsonparser.d#L450) or in the tokenization routine, I'd bet `C++` isn't treated as a single token.

**Comment by s-ludwig** [comment]
Thanks for investigating. I've fixed this now simply by adding  `C++` as a special token. Should make no difference in other places AFAICS.

**Comment by jpiles** [comment]
I'd say the only possible clash would be having the increment (`++`) operator on a variable really poorly called `C`, but even that shouldn't affect the doc generation tool (which is mainly concerned with function signatures, I guess)...

**Comment by s-ludwig** [comment]
Right, it only has to parse types and function declarations. There can be expressions in some places (default values, static array lengths), but the whole expression is simply treated as one anyway and isn't really parsed in detail, so it doesn't make a difference there.
