### ISSUE TITLE
ddox does not work if compiled with PIE

### ISSUE THREAD

**Issue by lodo1995** [rejectedsoftware/ddox#134]
On Ubuntu 16.10, with dmd configured to produced PIE executables (`-fPIC -defaultlib=libphobos2.so`), ddox compiles but does not run, with the following error:

```
Fatal Error while loading '/usr/lib/x86_64-linux-gnu/libphobos2.so.0.71':
        The module 'std.experimental.allocator.common' is already defined in '~/.dub/packages/ddox-0.15.15/ddox/ddox'.
Program exited with code 1
```

Looks like the `experimental_allocator` package is conflicting with the Phobos' `std.experimental.allocator` package.

**Comment by MartinNowak** [comment]
The experiment to copy modules w/ the same module really didn't went that well...

**Comment by MartinNowak** [comment]
BTW, does `-fPIC -defaultlib=libphobos2.so` work for you?
Might want to update the bug report, [Issue 5278 – gentoo's 'hardended' gcc doesn't work with dmd](https://issues.dlang.org/show_bug.cgi?id=5278).
