### ISSUE TITLE
marketing trumps reality

### ISSUE THREAD

**Issue by Extrawurst** [rejectedsoftware/ddox#140]
I cant seem to make this work. Both examples of ddox in real life (phobos and vibe.d) are light years apart from what one gets when following the instructions here on this site:
<img width="810" alt="screen shot 2017-01-07 at 04 31 27" src="https://cloud.githubusercontent.com/assets/776816/21739144/537ad7fa-d493-11e6-8ee1-f323b71ae724.png">

The dub integration to generate the ddox does not even generate anything meaningful currently because it is not able to build the docs.json (it simply is empty).

Any ideas how to make the ddox appear anyhow usable ?

**Comment by s-ludwig** [comment]
Looks like the default CSS needs some overhaul. You should generally get pretty close to the others by using the `--navigation-type=ModuleTree` switch, though.

**Comment by Extrawurst** [comment]
WOW that solves at least the issue with the nav-bar, now it much less noise. i actually did not know about that option because ddox --help does not suggest any of this because it is a command specific param :(

But I seriously suggest to make ModuleTree the default, the raw list is just insane :D

**Comment by ZombineDev** [comment]
@Extrawurst See Martin's project https://github.com/MartinNowak/scod for a good looking CSS based on ddox.

**Comment by Extrawurst** [comment]
@s-ludwig what do u think about making ModuleTree the default ?

**Comment by s-ludwig** [comment]
Making it the default indeed seems like the logical step. I'll do that!

**Comment by s-ludwig** [comment]
I think this can be closed now. master actually looks relatively pleasing now. Module tree is also the default.

**Comment by s-ludwig** [comment]
![image](https://cloud.githubusercontent.com/assets/1645969/24247633/c5ec6348-0fcc-11e7-9c2a-0bd2e15de598.png)
