### ISSUE TITLE
Group template/function overloads to avoid visual clutter

### ISSUE THREAD

**Issue by wilzbach** [rejectedsoftware/ddox#145]
There's currently an interesting discussion going on at the [NG](http://forum.dlang.org/post/zepezieoqidtvolqxolj@forum.dlang.org).

By accident `among` was compared between three doc engines:

DDox: https://dlang.org/library-prerelease/std/algorithm/comparison/among.html
DDoc: https://dlang.org/phobos/std_algorithm_comparison.html#.among
AdrDox: http://dpldocs.info/experimental-docs/std.algorithm.comparison.among.1.html

While they are essentially the same, I this is how the "out of the box" user experience looks like:
DDox (vanilla): http://files.wilzba.ch/dlang/ddoc_among/ddox/std/algorithm/comparison/among.html
Scod: http://files.wilzba.ch/dlang/ddoc_among/scod/std/algorithm/comparison/among.html

The biggest difference is that DDox essentially duplicates the documentation for every function and template of `among`. Ddoc and AdrDox group the overloads at the beginning and show the examples, parameters etc. only once.

**Comment by s-ludwig** [comment]
Fixed by #147.
