### ISSUE TITLE
Unmatched backticks on a single line should be output as is

### ISSUE THREAD

**Issue by s-ludwig** [rejectedsoftware/ddox#155]
Instead of rendering the rest of the line as inline code, single backtick characters should just be output as-is, as implied by the spec.

**Comment by CyberShadow** [comment]
For dlang.org we would probably prefer maximum strictness, though; a `$(BACKTICK)` isn't that much of an issue in cases where it's needed. I guess that could be done by a separate tool, like DScanner.
