### ISSUE TITLE
OpenSSL link errors related with vibed

### ISSUE THREAD

**Issue by CromFr** [rejectedsoftware/ddox#159]
Building a dub project documentation using `dub build --build=ddox` fails on Archlinux due to [OpenSSL ABI breakage](https://github.com/rejectedsoftware/vibe.d/issues/1758)

I think it would be great to add `versions "VibeNoSSL"` to ddox dub.sdl, since there is no point of serving the documentation with SSL enabled.

**Comment by wilzbach** [comment]
I agree - PR: https://github.com/rejectedsoftware/ddox/pull/188
