### ISSUE TITLE
Catch-22 when using ')' in code examples.

### ISSUE THREAD

**Issue by mleise** [rejectedsoftware/ddox#24]
Take this example of an example in DDoc:
```
 * Example:
 * ---
 * // Find an '$(RPAREN)' in a buffer of 1024 bytes using an additional sentinel.
 * size_t length = 1024;
 * char[] buffer = new char[](length+1);
 * buffer[length] = '$(RPAREN)';
 * auto pos = buffer.ptr.find!('$(RPAREN)');
 * if (pos < length) { // was an actual find before the sentinel }
 * ---
```
I had to use $(RPAREN) to silence DDox warnings about probably incorrect output for unmatched right parenthesis only to be warned that the character literal isn't terminated. In other words something expects '$' and cannot handle marcos that expand to a single character.

**Comment by s-ludwig** [comment]
This got fixed along the way by handling code blocks differently. Macros are not processed in code sections now.
