### ISSUE TITLE
GDC's 'type' in JSON file for extern(C) function returning pointer confuses DDOX

### ISSUE THREAD

**Issue by soltanmm** [rejectedsoftware/ddox#32]
Here's a file: http://pastebin.com/Fc0yS7Mr

Running `dmd -X main.d` and subsequently calling `ddox generate-html main.json doc` works to completion.

Running `dmd -fXf=main.json main.d` and subsequently calling `ddox generate-html main.json doc` causes this failure: `Expected function type for 'a*C ()'/'', got Pointer`

Given that the `type` field isn't even populated by the DMD JSON output, I'm not quite sure if this is a problem in GDC or in DDOX.

I've paste-binned the generated JSONs for GDC (http://pastebin.com/4JVQrybk) and DMD (http://pastebin.com/EfAbY1s6).

EDIT: A cursory glance over some other errors I'm getting suggests that DDOX has some trouble parsing function types with attributes.

**Comment by s-ludwig** [comment]
Current GDC versions now output the "deco" field.
