### ISSUE TITLE
Line doc comments handled wrong (DMD issue?)

### ISSUE THREAD

**Issue by Abscissa** [rejectedsoftware/ddox#58]
I'm not sure if this is an issue with ddox or dmd, but doc comments like this are handled wrong, which is a bit of a pain:

``` d
/// This function is here to aid in making your
/// software do cool stuff.
void foo() {}
```

ddox splits that into two ugly paragraphs:

```
This function is here to aid in making your

software do cool stuff.
```

Instead of:

```
This function is here to aid in making your software do cool stuff.
```

**Comment by s-ludwig** [comment]
Indeed is an issue in DMD, it gets output as `"This function is here to aid in making your\n\nsoftware do cool stuff.\n"` in the JSON document.

**Comment by s-ludwig** [comment]
https://issues.dlang.org/show_bug.cgi?id=14413

**Comment by s-ludwig** [comment]
@Abscissa can you have a look at the DMD issue? I'm in favor of your proposed behavior, but the bug report could use some more voices.

**Comment by Abscissa** [comment]
DMD Pull Request: https://github.com/D-Programming-Language/dmd/pull/4745

**Comment by s-ludwig** [comment]
Glad that this got through at last.
