### ISSUE TITLE
Build error in ddox/parsers/dparse

### ISSUE THREAD

**Issue by ivan-timokhin** [rejectedsoftware/ddox#60]
Building ddox master with dub fails with
    `source/ddox/parsers/dparse.d(275): Error: function vibe.data.serialization.name (string name) is not callable using argument types (AliasDeclaration)`

DMD 2.066.1

**Comment by s-ludwig** [comment]
Fixed by 0065d3086e6401e7ff57f1c898afe72759aa8a97
