### ISSUE TITLE
problems getting this to work on my project

### ISSUE THREAD

**Issue by kamisori** [rejectedsoftware/ddox#77]
Hello,
i am using dub (0.9.23) to build my project using gdc (Thread model: win32 gcc version 4.9.0 (crosstool-NG hg+unknown-20140610.075849 - 20140615-2.065-a8ad6a6678))  on mingw32/msys (just ran the mingw installer again to be sure it's up-to-date).

I decided i wanted my source to be nicely documented and since doxygen wouldnt generate anything i thought i would give ddox a try (mostly because i couldnt find a way to use the built in ddoc using dub. and i do not want to delve into how to use dmd just to get some docs.. well and secondly because the examples (vibe-d api documentation) did look nice)

so i added "ddox": "~>0.10.7" into my dependencies and later "subConfigurations": {"vibe-d": "win32"} because im running win7 64 (even though im using the 32bit version of gdc..) and now dub says the following:

$ dub build --force --compiler=gdc
Building vibe-d 0.7.23 configuration "libevent", build type debug.
Running gdc...
c:\dlang\gdc-i686-mingw32\include\d\4.9.0\gcc\backtrace.di:393: error: module unwind is in file 'gcc\unwind.d' which cannot be read
import path[0] = c:\dlang\gdc-i686-mingw32\include\d\4.9.0\i686-gdcproject-mingw32
import path[1] = c:\dlang\gdc-i686-mingw32\include\d\4.9.0
import path[2] = c:\users\mlatu\appdata\roaming\dub\packages\vibe-d-0.7.23\source
import path[3] = c:\users\mlatu\appdata\roaming\dub\packages\libevent-2.0.1_2.0.16
import path[4] = c:\users\mlatu\appdata\roaming\dub\packages\openssl-1.1.4_1.0.1g
FAIL C:\Users\mlatu\AppData\Roaming\dub\packages\vibe-d-0.7.23\.dub\build\libevent-debug-windows.mingw-x86-gdc_2065-EE237E1B6E15993750FE73780D656BF8\ vibe-d staticLibrary
Error executing command build:
gdc failed with exit code 1.

vverbose output is here:
http://pastebin.com/NVGT1WYz

edit:
im unsure if i need to get libevent and build it myself or if there is another way
edit2:
well i managed to install libevent but it did not change my situation
edit3:
well... since i now have found out how to pass the right switches to dmd this isnt very pressing anylonger.. even though i would very much like fancier documentation than that...

**Comment by s-ludwig** [comment]
Sorry that this got lost for so long, so not sure if this is still relevant. But it looks like there is something wrong with how GDC is set up. Both relevant files (backtrace.di and unwind.d) are just GDC internal files which are not directly used in either DUB, vibe.d or DDOX.

If this build problem persists, I'd recommend to download a version of dmd and then build the docs like this: `cd /path/to/project && dub build -b ddox --compiler=/path/to/dmd`
