### ISSUE TITLE
Link from enum member to enum

### ISSUE THREAD

**Issue by CyberShadow** [rejectedsoftware/ddox#78]
http://dlang.org/library/std/process/config.new_env.html

The only way to get from that page to the Config documentation in one click is by clicking the "Config" in the source code, where it's not styled as a link. The "Config" word in the title should probably be a link too.

**Comment by s-ludwig** [comment]
This was resolved as part of another issue some time ago. The title link now always links to the parent entity instead of to the module. (dlang.org-only fix)
