### ISSUE TITLE
Ddox replaces enum function default parameter with its integral value

### ISSUE THREAD

**Issue by FreeSlave** [rejectedsoftware/ddox#79]
So, that's not expected behavior.
Example:

``` d
///Enum description
enum Enum
{
    defaultValue,///default value
    anotherValue ///another value
}
///Somefunc
void someFunc(Enum e = Enum.defaultValue) {

}
```

Will produce:

``` d
void someFunc(
  Enum e = cast(Enum)0
);
```

Using dub build --build=ddox

**Comment by s-ludwig** [comment]
This appears to be fixed for recent DMD versions. I'm now getting something along the lines of `HTMLEscapeFlags flags = HTMLEscapeFlags.escapeNewline`.
