### ISSUE TITLE
Conflict of file names on Windows due to its case-insensitivity

### ISSUE THREAD

**Issue by MyLittleRobo** [rejectedsoftware/ddox#84]
If module declares two symbols equal in letters, but different in case, one of .html files generated by ddox will replace another.

Example:
```d
struct Case;
void case();
```

Will generate the only Case.html (or case.html)

**Comment by s-ludwig** [comment]
There is `--file-name-style=lowerUnderscored` (or `lowerCase`, `upperCase` or `upperUnderscore`) to work around that. On NTFS file systems it is in theory possible to use a case sensitive mode, but the `--file-name-style` solution is the only one that works for all file systems in general, such as FAT (it's really a file system issue and not an OS issue).

**Comment by s-ludwig** [comment]
See also #91 - there is a warning message on Windows and OS X now.
