### ISSUE TITLE
Functions in templates

### ISSUE THREAD

**Issue by CyberShadow** [rejectedsoftware/ddox#85]
This page is the first Google hit for "multisort site:dlang.org":

http://dlang.org/library-prerelease/std/algorithm/sorting/multi_sort.multi_sort.html

However, it is quite bare. There is no documentation and the signature is misleading. This seems to be the page for the function nested within the eponymous template declaration:

http://dlang.org/library-prerelease/std/algorithm/sorting/multi_sort.html

However, there is not even a link from the nested function to the properly-documented template declaration.

**Comment by s-ludwig** [comment]
The first page shouldn't be there at all, and Google probably picked it up, because it's also in sitemap.xml. During eponymous template detection, all template members are supposed to get removed from the documentation tree. I'll have a look.
