### ISSUE TITLE
Missing pages and incorrect links...

### ISSUE THREAD

**Issue by John-Colvin** [rejectedsoftware/ddox#91]
For an example, see https://github.com/DlangScience/dstats/blob/master/source/dstats/summary.d and its generated docs at https://dlangscience.github.io/dstats/api/dstats/summary.html

* ```struct Mean``` leads to a 404
* function ```mean``` leads to a page with name ```mean.html``` (note lowercase) which contains the docs from ```struct Mean```

**Comment by s-ludwig** [comment]
This is a problem with Windows' handling of file names with different case (one overwrites the other). Try using `--file-name-style=X`, where X is one of the lower or upper case styles, if you generate documentation on Windows.

I'll add a warning message if one of the affected styles is used on Windows.

**Comment by John-Colvin** [comment]
HFS+ is also case-insensitive by default on OS X, so almost all OS X users are affected by this also.

**Comment by s-ludwig** [comment]
Thanks, I've included `version (OSX)` for the warning.

**Comment by John-Colvin** [comment]
Presumably this means that ```dub build --build=ddox``` isn't a great idea on Windows or OS X, or is there some way of sending flags to ddox via dub?
