### ISSUE TITLE
Baked-in syntax highlighting

### ISSUE THREAD

**Issue by Abscissa** [rejectedsoftware/ddox#93]
Nothing in the syntax highlighting of a set of docs will ever need to change after the docs are built (aside from perhaps CSS tweaking), so there's no need for the highlighting to be dynamically-generated on-the-fly in JS.

It would be great if the current "prettify" tool could be replaced with an off-line version, such as [Dscanner's](https://github.com/Hackerpilot/Dscanner) ```--highlight``` feature.

**Comment by s-ludwig** [comment]
See #104.

**Comment by s-ludwig** [comment]
Implemented by merging #104.
