### ISSUE TITLE
Trailing newline/whitespace included in macro expansion

### ISSUE THREAD

**Issue by Abscissa** [rejectedsoftware/ddox#95]
Not sure if this is a ddox or dmd issue, but when there's a macro definition like this:

```
Macros:
	FOO = foo

	BAR = bar
```

(Note the blank line.)

The expansion of ```$(FOO)``` ends up being ```"foo\n\t"``` (ie, a trailing newline and tab) instead of ```"foo"```.

**Comment by MartinNowak** [comment]
ddox implements it's own macro expander
