### ISSUE TITLE
Regression in 10.0.6..10.0.9 - DDoc not parsed in some situations

### ISSUE THREAD

**Issue by CyberShadow** [rejectedsoftware/ddox#99]
Please see https://github.com/D-Programming-Language/dlang.org/pull/1108

**Comment by CyberShadow** [comment]
Thanks, will try this with the next version bump.

**Comment by s-ludwig** [comment]
I've opened https://github.com/D-Programming-Language/dlang.org/pull/1127 - seems to be alright.
